from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum

class AgentRoleEnum(str, Enum):
    INTAKE = "INTAKE"
    TRIAGE = "TRIAGE"
    APPOINTMENT = "APPOINTMENT"
    ACCOMMODATION = "ACCOMMODATION"
    PRESCRIPTION_OCR = "PRESCRIPTION_OCR"
    MEDICATION = "MEDICATION"
    DIET = "DIET"
    RECOVERY = "RECOVERY"
    THERAPY = "THERAPY"
    BILLING = "BILLING"
    FOLLOWUP = "FOLLOWUP"
    ESCALATION = "ESCALATION"
    DEVICE_ASSISTANCE = "DEVICE_ASSISTANCE"

class UrgencyLevelEnum(str, Enum):
    EMERGENCY = "EMERGENCY"
    URGENT = "URGENT"
    ROUTINE = "ROUTINE"

class ChatRequest(BaseModel):
    patient_id: Optional[str] = Field(None, alias="patientId")
    message: str
    language_override: Optional[str] = Field(None, alias="languageOverride")
    context: Optional[Dict[str, Any]] = Field(default_factory=dict)
    audio_base64: Optional[str] = Field(None, alias="audioBase64")

class AgentActionCard(BaseModel):
    card_type: str = Field(..., alias="cardType")
    data: Dict[str, Any]

class ChatResponse(BaseModel):
    response_message: str = Field(..., alias="responseMessage")
    audio_base64: Optional[str] = Field(None, alias="audioBase64")
    detected_language: str = Field(..., alias="detectedLanguage")
    is_code_mixed: bool = Field(False, alias="isCodeMixed")
    active_agent: AgentRoleEnum = Field(..., alias="activeAgent")
    action_card: Optional[AgentActionCard] = Field(None, alias="actionCard")
    urgency_classification: Optional[UrgencyLevelEnum] = Field(None, alias="urgencyClassification")
    requires_staff_escalation: bool = Field(False, alias="requiresStaffEscalation")
    context_updated: Dict[str, Any] = Field(default_factory=dict, alias="contextUpdated")

    class Config:
        populate_by_name = True

class LanguageDetectRequest(BaseModel):
    text: str

class LanguageDetectResponse(BaseModel):
    detected_language: str = Field(..., alias="detectedLanguage")
    confidence: float
    is_code_mixed: bool = Field(False, alias="isCodeMixed")
    transliterated_to_english: Optional[str] = Field(None, alias="transliteratedToEnglish")

    class Config:
        populate_by_name = True

class PrescriptionItemSchema(BaseModel):
    id: str
    medicine_name: str = Field(..., alias="medicineName")
    generic_name: Optional[str] = Field(None, alias="genericName")
    dosage: str
    form: str = "TABLET"
    frequency: str = "TWICE_DAILY"
    frequency_label: str = Field(..., alias="frequencyLabel")
    timing: str = "AFTER_MEALS"
    duration_days: int = Field(5, alias="durationDays")
    instructions: Optional[str] = None
    confidence: float = 1.0
    is_ambiguous: bool = Field(False, alias="isAmbiguous")

    class Config:
        populate_by_name = True

class PrescriptionOcrResponse(BaseModel):
    prescription_id: str = Field(..., alias="prescriptionId")
    items: List[PrescriptionItemSchema]
    overall_confidence: float = Field(..., alias="overallConfidence")
    requires_human_verification: bool = Field(True, alias="requiresHumanVerification")
    detected_notes: Optional[str] = Field(None, alias="detectedNotes")

    class Config:
        populate_by_name = True

class ConsultationSummaryRequest(BaseModel):
    patient_id: str = Field(..., alias="patientId")
    doctor_name: str = Field(..., alias="doctorName")
    transcript_turns: List[Dict[str, str]] = Field(..., alias="transcriptTurns")

class ConsultationSummaryResponse(BaseModel):
    summary_id: str = Field(..., alias="summaryId")
    chief_complaint: str = Field(..., alias="chiefComplaint")
    clinical_observations: List[str] = Field(default_factory=list, alias="clinicalObservations")
    prescribed_actions: List[str] = Field(default_factory=list, alias="prescribedActions")
    follow_up_advice: str = Field(..., alias="followUpAdvice")
    clinical_disclaimer: str = Field(
        "This automated consultation summary was generated by MediFlow AI Scribe to assist documentation and must be reviewed by the attending physician.",
        alias="clinicalDisclaimer"
    )

    class Config:
        populate_by_name = True
