export enum UserRole {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  ADMIN = 'ADMIN',
  STAFF = 'STAFF'
}

export enum UrgencyLevel {
  EMERGENCY = 'EMERGENCY', // Immediate clinical intervention (red)
  URGENT = 'URGENT',       // Prompt attention within 1-2 hours (amber)
  ROUTINE = 'ROUTINE'      // Standard outpatient scheduling (green)
}

export enum AppointmentType {
  VIRTUAL = 'VIRTUAL',
  DIRECT = 'DIRECT'
}

export enum AppointmentStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  IN_QUEUE = 'IN_QUEUE',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_CONSULTATION = 'IN_CONSULTATION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  MISSED = 'MISSED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED'
}

export enum RoomCategory {
  GENERAL_WARD = 'GENERAL_WARD',
  SEMI_PRIVATE = 'SEMI_PRIVATE',
  PRIVATE_DELUXE = 'PRIVATE_DELUXE',
  ICU = 'ICU',
  EMERGENCY_OBSERVATION = 'EMERGENCY_OBSERVATION'
}

export enum BedStatus {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  RESERVED = 'RESERVED',
  MAINTENANCE = 'MAINTENANCE',
  CLEANING = 'CLEANING'
}

export enum MedicationFrequency {
  ONCE_DAILY = 'ONCE_DAILY',       // 1-0-0 or 0-0-1
  TWICE_DAILY = 'TWICE_DAILY',     // 1-0-1
  THRICE_DAILY = 'THRICE_DAILY',   // 1-1-1
  FOUR_TIMES_DAILY = 'FOUR_TIMES_DAILY',
  AS_NEEDED = 'AS_NEEDED',         // PRN
  EVERY_4_HOURS = 'EVERY_4_HOURS',
  EVERY_6_HOURS = 'EVERY_6_HOURS',
  EVERY_8_HOURS = 'EVERY_8_HOURS'
}

export enum FoodTiming {
  BEFORE_MEALS = 'BEFORE_MEALS',
  AFTER_MEALS = 'AFTER_MEALS',
  WITH_MEALS = 'WITH_MEALS',
  EMPTY_STOMACH = 'EMPTY_STOMACH',
  ANYTIME = 'ANYTIME'
}

export enum DoseStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  DUE = 'DUE',
  TAKEN = 'TAKEN',
  MISSED = 'MISSED',
  SKIPPED = 'SKIPPED',
  SNOOZED = 'SNOOZED'
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  VERIFIED_BY_PATIENT = 'VERIFIED_BY_PATIENT',
  VERIFIED_BY_STAFF = 'VERIFIED_BY_STAFF',
  REJECTED = 'REJECTED'
}

export enum BillItemCategory {
  CONSULTATION = 'CONSULTATION',
  LAB_TEST = 'LAB_TEST',
  DIAGNOSTICS = 'DIAGNOSTICS',
  ACCOMMODATION = 'ACCOMMODATION',
  ROOM_CHARGES = 'ROOM_CHARGES',
  MEDICATION = 'MEDICATION',
  PHARMACY = 'PHARMACY',
  PROCEDURE = 'PROCEDURE',
  NURSING = 'NURSING',
  NUTRITION = 'NUTRITION',
  THERAPY = 'THERAPY',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY'
}

export enum BillingStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  DISPUTED = 'DISPUTED',
  WAIVED = 'WAIVED'
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  ESCALATED = 'ESCALATED',
  SKIPPED = 'SKIPPED'
}

export enum EscalationSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum LanguageCode {
  ENGLISH = 'en',
  TELUGU = 'te',
  HINDI = 'hi'
}

export enum NotificationType {
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  MEDICATION_REMINDER = 'MEDICATION_REMINDER',
  QUEUE_UPDATE = 'QUEUE_UPDATE',
  ROOM_ALLOCATION = 'ROOM_ALLOCATION',
  THERAPY_REMINDER = 'THERAPY_REMINDER',
  BILLING_STATEMENT = 'BILLING_STATEMENT',
  ESCALATION_ALERT = 'ESCALATION_ALERT',
  GENERAL_ALERT = 'GENERAL_ALERT',
  MISSED_APPOINTMENT = 'MISSED_APPOINTMENT'
}
